config/routes.rb
Rails.application.routes.draw do
  get '/sign_up', to:'users#sign_up', as: :sign_up
  post '/sign_up', to:'users#sign_up_process'
  get '/sign_in', to:'users#sign_in', as: :sign_in
  post '/sign_in', to:'users#sign_in_process'
  get '/sign_out', to:'users#sign_out', as: :sign_out
  get '/', to:'users#top'
  get '/top', to:'users#top', as: :top
  get '/posts/new', to:'posts#new', as: :new_post
  post '/posts', to:'posts#create'
  delete '/posts/(:id)', to:'posts#destroy', as: :post
  post '/posts/(:id)/comment', to:'posts#comment', as: :comment
  get '/posts/(:id)/like', to: 'posts#like', as: :like
  get '/profile/(:id)', to:'users#show', as: :profile
  get '/profile/(:id)/edit', to:'users#edit', as: :profile_edit
  post '/profile/(:id)/edit', to:'users#update'
  get '/follow/(:id)', to: 'users#follow', as: :follow
  get '/follow_list/(:id)', to:'users#follow_list', as: :follow_list
  get '/follower_list/(:id)', to:'users#follower_list', as: :follower_list
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :user
  belongs_to :follow_user, class_name: "User"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_images, dependent: :destroy
  has_many :post_likes, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  paginates_per 3
  def like_from?(user)
    self.post_likes.exists?(user_id: user.id)
  end  
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  belongs_to :post
end

app/models/post_like.rb
class PostLike < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :posts
    has_many :post_likes
    has_many :post_comments
    has_many :follows
    has_many :followers, foreign_key: :follow_user_id, class_name:"Follow"
    before_create :convert_password
    def convert_password
        self.password = User.generate_password(self.password)
    end
    
    def self.generate_password(password)
        salt = "h!hgamcRAdh38bajhvgai17ysvb"
        Digest::MD5.hexdigest(salt + password)
    end
    def followed_by?(user)
        user.follows.exists?(follow_user_id: self.id)
    end    
      VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i 
      validates :name, presence: true
      validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, uniqueness: true
      validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include UsersHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authorize
  #新規投稿ページ
  def new
    @post = Post.new
  end
  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:message] = "投稿を削除しました。"
      redirect_to top_path and return
    else
      flash[:danger] = "削除に失敗しました。"
      redirect_to top_path and return      
    end  
  end   
  def create
    # ここに処理を実装
    @post = Post.new(post_params)
    upload_file = params[:post][:upload_file]
    #投稿画像がない場合
    if upload_file.blank?
        flash[:danger] = "投稿には画像が必須です。"
        redirect_to new_post_path and return
    end  
    upload_file_name = upload_file.original_filename
    output_dir = Rails.root.join('public', 'images')
    output_path = output_dir + upload_file_name
    @post.post_images.new(name: upload_file_name)
    File.open(output_path, 'w+b') do |f|
        f.write(upload_file.read)
    end 
    if @post.save
        flash[:message] = "投稿しました。"
        redirect_to top_path and return
    else
        flash[:danger] = "投稿に失敗しました。"
        redirect_to new_post_path and return
    end  
  end
  def like
    @post = Post.find(params[:id])
    if PostLike.exists?(post_id: @post.id, user_id: current_user.id)
      PostLike.find_by(post_id: @post.id, user_id: current_user.id).destroy
    else
      PostLike.create(post_id: @post.id, user_id: current_user.id)
    end
    redirect_to top_path and return
  end
  def comment
    @post = Post.find(params[:id])
    @post.post_comments.create(post_comment_params)
    redirect_to top_path and return
  end
  def post_comment_params
    params.require(:post_comment).permit(:comment).merge(user_id: current_user.id)
  end
  private
  def post_params
      params.require(:post).permit(:caption).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, except: [:sign_up, :sign_up_process, :sign_in, :sign_in_process]
  before_action :redirect_to_top_if_signed_in, only: [:sign_up, :sign_in]
  
  def sign_out
    user_sign_out
    redirect_to sign_in_path and return
  end  
  def top
    if params[:word].present?
      @posts = Post.where("caption like ?", "%#{params[:word]}%").order("id desc")
    else
      @posts = Post.all.order("id desc").page(params[:page])
    end
    @recommends = User.where.not(id: current_user.id).where.not(id: current_user.follows.pluck(:follow_user_id)).limit(3)
  end
  def show
    #ここに処理を実装
    @user = User.find(params[:id])
    @posts = Post.where(user_id: @user.id)
  end
  def edit
    @user = User.find(current_user.id)
  end
  def update
    upload_file = params[:user][:image]
    if upload_file.present?
      upload_file_name = upload_file.original_filename
      output_dir = Rails.root.join('public', 'users')
      output_path = output_dir + upload_file_name
      File.open(output_path, 'w+b') do |f|
        f.write(upload_file.read)
      end
      current_user.update(user_params.merge({image: upload_file.original_filename}))
    end
    current_user.update(user_params)
    redirect_to profile_path(current_user)
  end
  def sign_up
    @user = User.new
    render layout: "application_not_login"
  end
  def sign_up_process
    user = User.new(user_params)
    if user.save
      user_sign_in(user)
      redirect_to top_path and return
    else
      flash[:dager] = "ユーザー登録に失敗しました。"
      redirect_to sign_up_path and return 
    end
  end
  def sign_in
    @user = User.new
    render layout: "application_not_login"
  end
  def sign_in_process
      #　ここに処理を実装
      password_md5 = User.generate_password(user_params[:password])
      user = User.find_by(email: user_params[:email], password: password_md5)
      if user
         user_sign_in(user)
         redirect_to top_path and return
      else
        flash[:danger] = "サインインに失敗しました。"
        redirect_to('/sign_in')
      end  
  end
  def follow
    @user = User.find(params[:id])
    if Follow.exists?(user_id: current_user.id, follow_user_id: @user.id)
      Follow.find_by(user_id: current_user.id, follow_user_id: @user.id).destroy
    else
      Follow.create(user_id: current_user.id, follow_user_id: @user.id)
    end
    redirect_back(fallback_location: top_path, notice: "フォローを更新しました")
  end
  def follow_list
    #プロフィールの情報を取得
    @user = User.find(params[:id])
    @users = User.where(id: Follow.where(user_id: @user.id).pluck(:follow_user_id))
  end
  def follower_list
    @user = User.find(params[:id])
    @users = User.where(id: Follow.where(follow_user_id: @user.id).pluck(:user_id))
  end
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :comment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def user_sign_in(user)
        session[:user_id] = user.id
    end
    def current_user
        if @current_user.nil?
            @current_user = User.find_by(id: session[:user_id])
        else
            @current_user
        end    
    end    
    #def current_user
    #    User.find_by(id: session[:user_id])
    #end
    def user_sign_out
        session.delete(:user_id)
        @current_user = nil
    end
    def user_signed_in?
        current_user.present?
    end
    def authorize
        redirect_to sign_in_path unless user_signed_in?
    end
    def redirect_to_top_if_signed_in
        redirect_to top_path and return if user_signed_in?
    end
    def image_url(user)
        if user.image.blank?
            "https://dummyimage.com/200x200/000/fff"
        else
            "/users/#{user.image}"
        end    
    end    
    
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
  </head>
  <body class="logined">
    <header class="global_header">
      <!-- ロゴ -->
      <div class="icon">
        <%= link_to top_path do %>
          <i class="fa fa-camera"></i>
        <% end %>
      </div>
      <%= link_to top_path do%>
       <h1 class="logo">Photo</h1>
      <% end %>
      <!-- 検索フォーム -->
      <form class="search">
        <input type="text" placeholder="検索ワードを入力" name="word" value="">
      </form>
      <!-- メニュー -->
      <ul class="menu">
        <li>
          <!-- サインアウト -->
          <%= link_to sign_out_path do %>
            <i class="fa fa-sign-out"></i>
          <% end %>
        </li>
        <li>
          <!-- プロフィールページ -->
          <%= link_to profile_path(current_user) do %>
            <i class="fa fa-user-o"></i>
          <% end %>
        </li>
        <li>
          <!-- 投稿 -->
          <%= link_to new_post_path do %>
            <i class="fa fa-upload"></i>
          <% end %>
        </li>
      </ul>
    </header>
    <% flash.each do |type, message| %>
    <div class="alert alert-<%= type%>"><%= message %></div>
    <% end %>
    <%= yield %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script>
        window.setTimeout(function() {
              $(".alert").slideUp();
        }, 3000);
    </script>
  </body>
</html>

app/views/layouts/application_not_login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photo</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%  flash.each do |type, message| %>
      <div class = "alert alert-<%= type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script>
      window.setTimeout(function() {
        $(".alert").slideUp();
      }, 3000);
    </script>
  </body>
</html>

app/views/posts/new.html.erb
<div class="container">
  <div class="new_post_wrap">
    <h1>新規Photo投稿</h1>
    <%= form_for @post do |f| %>
      <!-- ファイル選択ボタン -->
      <div class="file_wrap">
        <%= f.file_field :upload_file %>
      </div>
      <!-- 説明文 -->
      <div class="textarea_wrap">
        <%= f.text_area :caption, placeholder: "写真に対する説明文を入力" %>
      </div>
      <!-- 送信ボタン -->
      <div class="btn_wrap">
        <%= f.submit "送信" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/_profile.html.erb
<div class="profile">
  <div class="image">
    <div style="background: url('<%= image_url(@user) %>'); background-position: 50%; background-size: cover;"></div>
  </div>
  <div class="info">
    <div class="name">
      <h1><%= @user.name %></h1>
      <div class="actions">
        <% if @user.id == current_user.id %>
        <div class="edit">
          <%= link_to "プロフィール編集", profile_edit_path %>
        </div>
        <% else %>
        <div class="follow">
          <%= link_to @user.followed_by?(current_user)? "フォロー解除": "フォローする", follow_path(@user.id) %>
        </div>
        <% end %>
      </div>
    </div>
    <div class="status">
      <p class="posts_count">投稿数<%= @user.posts.length %>件</p>
      <p class="follower_count"><%= link_to "#{@user.follows.length}人のフォロワー", follower_list_path(@user) %></p>
      <p class="follow_count"><%= link_to "フォロー#{@user.follows.length}人", follow_list_path(@user) %></p>
    </div>
    <div class="comment">
      <%= @user.comment %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="profile_edit container">
  <%= form_for @user, url: profile_edit_path, method: :post do |f| %>
    <div class="field">
      <%= f.label :name, "名前" %>
      <%= f.text_field :name, placeholder: "名前を入力して下さい。" %>
    </div>
    <div class="field">
      <%= f.label :email, "メールアドレス" %>
      <%= f.text_field :email, placeholder: "メールアドレスを入力して下さい。" %>
    </div>
    <div class="field">
      <%= f.label :comment, "コメント" %>
      <%= f.text_field :comment, placeholder: "自己紹介など" %>
    </div>
    <div class="field">
      <label>プロフィール画像</label>
      <div class="file_wrap">
        <%= f.file_field :image %>
      </div>
    </div>
    <div class="button_wrap">
      <input type="submit" value="保存する" class="button">
    </div>
  <% end %>
</div>

app/views/users/follow_list.html.erb
<div class="user container">
  <!-- プロフィール部分 -->
  <%= render partial: 'users/profile' %>
  <!-- フォローリスト部分 -->
  <h1>フォロー</h1>
  <% if @users.any? %>
  <ul class="users">
    <% @users.each do |user| %>
    <li>
      <div style="background: url('<%= image_url(user) %>'); background-position: 50%; background-size: cover;" class="image"></div>
      <%= link_to profile_path(user) do %>
      <span class="name"><%= user.name %></span>
      <% end %>
      <%= link_to user.followed_by?(current_user)? "フォロー解除": "フォローする", follow_path(user.id), class: "button" %>
    </li>
    <% end %>
  </ul>
  <% else %>
   <p class="empty">ユーザーが存在しません。</p>
  <% end %>
</div>

app/views/users/follower_list.html.erb
<div class="user container">
  <!-- プロフィール部分 -->
  <% render partial: "users/profile" %>
  <!-- フォロワーリスト部分 -->
  <h1>フォロワー</h1>
  <% if @users.any? %>
    <% @users.each do |user| %>
    <ul class="users">
      <li>
        <div style="background: url('<%= image_url(user) %>'); background-position: 50%; background-size: cover;" class="image"></div>
        <%= link_to profile_path(user) do %>
        <span class="name"><%= user.name %></span>
        <% end %>
        <%= link_to user.followed_by?(current_user)? "フォロー解除": "フォローする", follow_path(user.id), class: "button" %>
      </li>
    </ul>
    <% end %>
  <% else %>
    <p class="empty">ユーザーが存在しません。</p>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="user container">
  <!-- プロフィール部分 -->
  <%= render partial: 'users/profile' %>
  <!-- 投稿画像部分 -->
  <div class="posts">
    <ul>
      <% @posts.each do |post| %>
        <% post.post_images.each do |post_image| %>
      <li>
        <div style="background: url('<%= "/images/#{post_image.name}"  %>'); background-repeat: no-repeat; background-position: 50%;"></div>
      </li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/sign_in.html.erb
<% @user = User.new unless @user %>
<div class="sign_in">
  <div class="contents">
    <div class="sign_in_form">
      <h1>Photo</h1>
      <%= form_for @user, url: sign_in_path do |f| %>
        <div class="field">
          <%= f.email_field :email, placeholder: "メールアドレス" %>
        </div>
        <div class="field">
          <%= f.password_field :password, placeholder: "パスワード" %>
        </div>
        <button>サインインする</button>
      <% end %>
    </div>
    <div class="sign_in_link">
      <p>アカウントをお持ちですか？ <%= link_to "新規登録する", sign_up_path %></p>
    </div>
  </div>
</div>

app/views/users/sign_up.html.erb
<div class="sign_up">
  <div class="contents">
    <div class="sign_up_form">
      <h1>Photo</h1>
      <p>友達のphotoをチェックしよう</p>
      <%= form_for @user, url: sign_up_path do |f| %>
        <div class="field">
          <%= f.text_field :name, placeholder: "ユーザーネーム" %>
        </div>
        <div class="field">
          <%= f.email_field :email, placeholder: "メールアドレス" %>
        </div>
        <div class="field">
          <%= f.password_field :password, placeholder: "パスワード"%>
        </div>
        <button>登録する</button>
      <% end %>
    </div>
    <div class="sign_in_link">
      <p>アカウントをお持ちですか？ <%= link_to "サインインする", sign_in_path %></p>
    </div>
  </div>
</div>

app/views/users/top.html.erb
<div class="top container">
  <% if @posts.any? %>
  <ul class="posts">
    <!-- 投稿画像１つめ -->
    <div><%= page_entries_info @posts %></div>
    <% @posts.each do |post| %>
    <li>
      <div class="user">
      <div style="background: url('<%= image_url(post.user) %>'); background-position: center; background-size: cover" class="image"></div>
      <p><%= link_to post.user.name, profile_path(post.user) %></p>
      </div>
      <% post.post_images.each do |post_image| %>
      <div class="image_wrap">
        <%= image_tag "/images/#{post_image.name}" %>
      </div>
      <% end %>
      <!-- テキスト部分 -->
      <div class="info">
        <div class="action">
          <%= link_to like_path(post) do %>
            <i class="fa <%= post.like_from?(current_user)? "fa-heart active" : "fa-heart-o" %>"></i>
          <% end %>
          <label for="post-comment-">
            <i class="fa fa-comment-o"></i>
          </label>
          <% if post.user_id == current_user.id %>
            <%= link_to post_path(post), method: :delete do %>
              <i class="fa fa-close"></i>
            <% end %>  
          <% end %>
        </div>
        <div class="like">
          <p>いいね 3件</p>
        </div>
      <div class="comment">
      <% if post.caption.present? %>
      <ul>
      <li>
      <span class="user_name"><%= post.user.name %></span>
      <span class="caption"><%= post.caption %></span>
      </li>
      <% post.post_comments.each do |post_comment| %>
      <li>
        <span class="user_name"><%= post_comment.user.name %></span>
        <span class="caption"><%= post_comment.comment %></span>
      </li>
      <% end %>
      </ul>
      <div class="text_wrap">
        <%= form_for post.post_comments.new, url: comment_path(post) do |f| %>
          <div class="field">
            <%= f.text_field :comment, id: "post-comment-#{post.id}", placeholder: "コメントを入力" %>
            <%= f.submit"送信" %>
          </div>
        <% end %>
      </div>
      <% end %>
      </div>
    </li>  
    <% end %>
    <div><%= paginate @posts %></div>
  </ul>
  <% else %>
  <P class="empty">投稿がありません</p>
  <% end %>
  </div>
  <!-- おすすめユーザー -->
  <% if @recommends.any? %>
  <div class="recommend">
    <h2>おすすめ</h2>
    <ul>
      <% @recommends.each do |user| %>
      <li>
      <%= link_to profile_path(user) do %>
        <img src="<%= image_url(user) %>">
        <p><%= user.name %></p>
      <% end %>
      <%= link_to "フォローする", follow_path(user), class: "button" %>
      </li>
      <% end %>
    </ul>
  </div>
  <% end %>
</div>